services:
  ec_backend:
    container_name: "ec_backend"
    build:
      context: ./backend
      dockerfile: ./config/develop/docker/Dockerfile
    ports:
      - "8000:80"
    networks:
      ec_network:
        ipv4_address: 192.168.157.60
    volumes:
      - .:/var/www/html
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  ec_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.157.0/24
