export const IconEnum = {
    home: 'lucide:house',
    handCoins: 'lucide:hand-coins',
    check: 'lucide:check',
    user: 'lucide:user',
    shoppingCart: 'lucide:shopping-cart',
    logOut: 'lucide:log-out',
    trash2: 'lucide:trash-2',
    eye: 'lucide:eye',
    eyeOff: 'lucide:eye-off',
    search: 'lucide:search',
    pencil: 'lucide:pencil',
    sun: 'lucide:sun',
    moon: 'lucide:moon',
}
